offset:
  head_pitch: 0
  head_roll: 0
  head_yaw: 0
  l_ankle_pitch: 0
  l_ankle_roll: 0
  l_elbow_pitch: 0
  l_hip_pitch: 0
  l_hip_roll: 0
  l_hip_yaw: 0
  l_knee_pitch: 0
  l_shoulder_pitch: 0
  l_shoulder_roll: 0
  r_ankle_pitch: 0
  r_ankle_roll: 0
  r_elbow_pitch: 0
  r_hip_pitch: 0
  r_hip_roll: 0
  r_hip_yaw: 0
  r_knee_pitch: 0
  r_shoulder_pitch: 0
  r_shoulder_roll: 0
  waist_roll: 0
  waist_yaw: 0
